[package]
name = "saws"
version = "0.1.0"
edition = "2021"
default-run = "test_server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite="0.18.0"

[[bin]]
name = "test_server"
path = "src/test_server.rs"
